import Head from "next/head";
import Layout from "@/components/Layout";
import Link from "next/link";

export const metadata = {
  title: "Terms of Use",
  description: "Read our Terms of Use to understand the rules and guidelines when using OpEn Platform.",
  openGraph: {
    title: "Terms of Use - OpEn",
    description: "Read our Terms of Use to understand the rules and guidelines when using OpEn Platform.",
    url: "https://yourcompany.com/terms-of-use",
    type: "website",
  },
  twitter: {
    card: "summary_large_image",
  },
};

export default function Home() {
  return (
    <Layout>
      <Head>
        <title>Terms of Use - OpEn</title>
      </Head>
      <main className="main">
        <section id="terms-of-use" className="section why-us">
          <div className="page-title mb-5" data-aos="fade-up" data-aos-delay={100}>
            <div className="heading">
              <div className="container">
                <div className="row d-flex justify-content-center text-center">
                  <div className="col-lg-8">
                    <h1>Terms of Use</h1>
                  </div>
                </div>
              </div>
            </div>
          </div>
          <div className="container">
            <div className="row gy-12 d-flex">
              <div className="col-lg-12 d-flex">
                <div className="row gy-12" data-aos="fade-up" data-aos-delay={200}>
                  <div className="col-xl-12" data-aos="fade-up" data-aos-delay={400}>
                    <div className="flex-column">

                      <div id="intellectual-property">
                        <h2>1. Intellectual Property</h2>
                        <p>
                          All content, features, and functionality available on the OpEn platform — including but not limited to text, graphics, logos, icons, visual design, audio, video, AI-generated content, toolkits, templates, frameworks, and course materials — are the intellectual property of OpEn Digital and are protected by applicable copyright, trademark, and other intellectual property laws.
                        </p>
                        <p><strong>a. Ownership of AI-Generated Content</strong></p>
                        <ul>
                          <li>
                            You may use business documents and outputs generated by Lift AI for your personal or business use. However, the underlying AI system, structure, and prompt framework remain the exclusive property of OpEn.
                          </li>
                          <li>
                            You are prohibited from reselling, redistributing, or claiming ownership over Lift AI-generated materials as templates or tools for commercial resale without express written permission.
                          </li>
                        </ul>
                        <p><strong>b. Course Content and Resources</strong></p>
                        <ul>
                          <li>
                            All course content, including video lectures, workbooks, frameworks, and downloadable materials, are licensed for personal learning only. Public broadcasting, distribution, or reuse for teaching or commercial purposes is strictly prohibited.
                          </li>
                        </ul>
                        <p><strong>c. Community Contributions</strong></p>
                        <ul>
                          <li>
                            By posting content (text, comments, files, media) in OpEn Tribes, MyTribers, or other collaborative areas, you grant OpEn a non-exclusive, royalty-free license to use, display, and adapt that content only for platform-related purposes (e.g., moderation, presentation, or product improvement).
                          </li>
                        </ul>
                        <p><strong>d. Trademarks and Branding</strong></p>
                        <ul>
                          <li>
                            All OpEn logos, names, and brand elements are owned by OpEn Digital. You may not use them without prior written approval, except where permitted by fair use or marketing collaboration.
                          </li>
                        </ul>
                      </div>

                      <div id="use-of-platform-content">
                        <h2>2. Use of Platform Content</h2>
                        <p>
                          By accessing the OpEn platform, you are granted a limited, non-exclusive, non-transferable, and revocable license to use the platform’s content and services solely for your personal or business development purposes in accordance with these Terms.
                        </p>
                        <p><strong>a. Acceptable Use</strong></p>
                        <ul>
                          <li>Learning and applying entrepreneurship skills</li>
                          <li>Creating internal documents using Lift AI</li>
                          <li>Engaging with other users for collaboration and discussion</li>
                          <li>Accessing recommended business tools and templates for your business</li>
                        </ul>
                        <p><strong>b. Prohibited Use</strong></p>
                        <ul>
                          <li>Share your account or subscription with others</li>
                          <li>Republish or resell any OpEn content, tool directory, or course materials</li>
                          <li>Use Lift AI to create content for resale, duplication, or resale as generic templates</li>
                          <li>Use the platform in any manner that violates intellectual property rights or local laws</li>
                        </ul>
                        <p><strong>c. Token-Based Features (Lift AI &amp; Others)</strong></p>
                        <ul>
                          <li>
                            Some features (e.g., Lift AI outputs, document generation, business templates) require tokens. You may not attempt to bypass token restrictions or automate prompt submissions.
                          </li>
                        </ul>
                        <p><strong>d. Platform Integrity</strong></p>
                        <ul>
                          <li>
                            You agree not to reverse-engineer, copy, or disrupt any part of the platform, including AI features, user interface components, or backend processes.
                          </li>
                        </ul>
                      </div>

                      <div id="user-registration-account">
                        <h2>3. User Registration &amp; Account</h2>
                        <p>
                          To access most features on the OpEn platform, you must create an account and provide accurate and complete information.
                        </p>
                        <p><strong>a. Registration Requirements</strong></p>
                        <ul>
                          <li>You must be at least 18 years old and legally capable of entering into a binding agreement.</li>
                          <li>You agree to provide true, current, and complete registration details — including name, email address, and business profile data.</li>
                          <li>You may update your profile at any time via your account settings.</li>
                        </ul>
                        <p><strong>b. Subscription Tiers</strong></p>
                        <ul>
                          <li>Basic Users: Free tier with access to limited features (e.g., MyTribers, Business Tools, token-purchased AI access).</li>
                          <li>Premium Users: Paid subscription with access to Lift AI (with discounted tokens), full training modules, enhanced support, and priority features.</li>
                        </ul>
                        <p><strong>c. Account Security</strong></p>
                        <ul>
                          <li>You are responsible for maintaining the confidentiality of your login credentials and for all activity under your account.</li>
                          <li>You agree to notify us immediately if you suspect unauthorized access to your account.</li>
                        </ul>
                        <p><strong>d. Multi-Device Use &amp; Sharing</strong></p>
                        <ul>
                          <li>You may access your account from multiple personal devices but may not share your login with others or use it for group/team access unless explicitly permitted.</li>
                        </ul>
                        <p><strong>e. Suspension or Termination</strong></p>
                        <ul>
                          <li>OpEn reserves the right to suspend or terminate your account at any time for violations of these Terms, misuse of AI tools, abuse of community features, or fraudulent behavior.</li>
                        </ul>
                      </div>

                      <div id="user-generated-content-community">
                        <h2>4. User-Generated Content &amp; Community Use</h2>
                        <p>
                          As a platform designed for collaboration and peer support, OpEn allows users to contribute content in areas such as Tribes, MyTribers, discussions, and profile spaces. By submitting or posting any content, you agree to the following:
                        </p>
                        <p><strong>a. Ownership &amp; License</strong></p>
                        <ul>
                          <li>
                            You retain ownership of any original content you post. However, by submitting content, you grant OpEn a non-exclusive, royalty-free, worldwide license to use, display, reproduce, and adapt your content solely for purposes of operating and improving the platform.
                          </li>
                        </ul>
                        <p><strong>b. Acceptable Conduct</strong></p>
                        <ul>
                          <li>No harassment, hate speech, or discriminatory language</li>
                          <li>No promotion of scams, illegal activity, or misinformation</li>
                          <li>No mass messaging, spamming, or unauthorized advertising</li>
                          <li>No sharing of copyrighted or confidential material without permission</li>
                        </ul>
                        <p><strong>c. Moderation &amp; Enforcement</strong></p>
                        <ul>
                          <li>OpEn reserves the right to remove any content that violates these Terms or is deemed inappropriate.</li>
                          <li>Repeated violations may result in suspension or permanent removal from community features or the entire platform.</li>
                        </ul>
                        <p><strong>d. Public Visibility</strong></p>
                        <ul>
                          <li>Certain information you submit (e.g., your profile bio, business focus, location, or posts in Tribes) may be visible to other users. You are responsible for the content you choose to share.</li>
                        </ul>
                      </div>

                      <div id="ai-powered-features">
                        <h2>5. AI-Powered Features, Token Usage &amp; Limitations</h2>
                        <p>
                          The OpEn platform includes AI-powered services such as Lift AI and other automated features to assist users with business document creation, analysis, and decision support.
                        </p>
                        <p><strong>a. AI Functionality Disclaimer</strong></p>
                        <ul>
                          <li>Lift AI and other AI features provide guidance based on user inputs but do not constitute legal, financial, or regulatory advice.</li>
                          <li>AI outputs are informational tools only and should be reviewed before being used for official or external purposes.</li>
                        </ul>
                        <p><strong>b. Guided Prompting &amp; User Responsibility</strong></p>
                        <ul>
                          <li>Lift AI uses guided prompts to help users refine their queries. You are responsible for ensuring that any information provided to the AI is accurate and complete.</li>
                          <li>We do not review AI outputs in real time; you are solely responsible for how you use the content generated.</li>
                        </ul>
                        <p><strong>c. Token Usage Policy</strong></p>
                        <ul>
                          <li>Certain features (e.g., document generation, consulting simulation) require tokens. Tokens are non-refundable once used.</li>
                          <li>Premium users receive tokens at discounted rates and may access Lift AI under capped usage limits.</li>
                          <li>Basic users can purchase tokens to access these features on a per-use basis.</li>
                          <li>Attempting to automate, manipulate, or overload token systems is prohibited and may result in account suspension.</li>
                        </ul>
                        <p><strong>d. Downloadable Outputs</strong></p>
                        <ul>
                          <li>You may download AI-generated outputs (e.g., PDF, DOCX) for business use. However, redistribution or resale of these documents as commercial templates or services is not permitted without written permission.</li>
                        </ul>
                        <p><strong>e. Limitations of Liability</strong></p>
                        <ul>
                          <li>OpEn is not liable for any losses, damages, or decisions made based on AI-generated outputs. Always verify critical outputs with a qualified professional when needed.</li>
                        </ul>
                      </div>

                      <div id="course-access-certifications">
                        <h2>6. Course Access, Certifications &amp; Use Limitations</h2>
                        <p>
                          OpEn provides access to entrepreneurship training content through its online learning modules. These courses are designed to offer practical, self-paced education for business growth.
                        </p>
                        <p><strong>a. Access Based on Subscription Tier</strong></p>
                        <ul>
                          <li>Premium users receive full access to all course modules during their subscription period.</li>
                          <li>Basic users cannot access courses unless they upgrade to Premium.</li>
                          <li>Access may include video lessons, interactive workbooks, downloadable resources, and assessments.</li>
                        </ul>
                        <p><strong>b. License for Use</strong></p>
                        <ul>
                          <li>Course materials are licensed for personal use only. You may not copy, share, or republish this content for commercial, academic, or training purposes without written permission from OpEn.</li>
                        </ul>
                        <p><strong>c. Certifications</strong></p>
                        <ul>
                          <li>Upon completion of eligible courses, you may receive a digital certificate of participation.</li>
                          <li>These certificates are not affiliated with any accredited academic institution and do not confer formal degrees or licenses.</li>
                        </ul>
                        <p><strong>d. Lifetime Access &amp; Availability</strong></p>
                        <ul>
                          <li>Course access is limited to the duration of your Premium subscription. You may lose access upon downgrade or cancellation unless otherwise stated.</li>
                        </ul>
                        <p><strong>e. Content Updates</strong></p>
                        <ul>
                          <li>We may update, improve, or replace course modules over time to reflect changes in business best practices or user needs. We are not obligated to retain or reissue expired modules.</li>
                        </ul>
                      </div>

                      <div id="tools-directory">
                        <h2>7. Tools Directory and Third-Party Recommendations</h2>
                        <p>
                          OpEn provides a curated directory of digital tools, platforms, and services (the “Startup Growth Toolkit”) designed to support entrepreneurs in areas such as marketing, finance, operations, HR, and legal compliance.
                        </p>
                        <p><strong>a. Curated Tools Directory</strong></p>
                        <ul>
                          <li>Tools listed in the directory are selected based on their affordability, relevance, and utility for entrepreneurs operating on a lean budget.</li>
                          <li>Tools are categorized by function (e.g., finance, CRM, project management) and may include summaries, ratings, or affiliate links.</li>
                        </ul>
                        <p><strong>b. Third-Party Access</strong></p>
                        <ul>
                          <li>Clicking on a tool link may direct you to a third-party website or service not owned or operated by OpEn. We are not responsible for the content, functionality, or practices of these external platforms.</li>
                        </ul>
                        <p><strong>c. No Endorsement Guarantee</strong></p>
                        <ul>
                          <li>While tools are researched and recommended in good faith, listing a product in our directory does not constitute an endorsement, warranty, or guarantee of its performance, security, or business outcomes.</li>
                        </ul>
                        <p><strong>d. Premium Tool Access (If Offered)</strong></p>
                        <ul>
                          <li>Some tools or services may be offered at a discount or through special partnerships for Premium users. Access to these offers is subject to availability and may be revoked or changed at any time.</li>
                        </ul>
                        <p><strong>e. User Responsibility</strong></p>
                        <ul>
                          <li>You are responsible for reviewing any third-party terms of use and privacy policies before using their services. Your engagement with those tools is solely at your own discretion and risk.</li>
                        </ul>
                      </div>

                      <div id="payments-tokens-refunds">
                        <h2>8. Payments, Tokens, Refunds &amp; Downgrades</h2>
                        <p>
                          OpEn operates on a subscription-based and token-based model for accessing certain platform features, including Lift AI and learning modules.
                        </p>
                        <p><strong>a. Subscription Billing</strong></p>
                        <ul>
                          <li>Premium plans are billed monthly or annually depending on your selection. Your payment method will be charged automatically at the beginning of each billing cycle unless you cancel or downgrade your plan in advance.</li>
                          <li>You are responsible for maintaining a valid payment method on file.</li>
                        </ul>
                        <p><strong>b. Token-Based Transactions</strong></p>
                        <ul>
                          <li>Some features (e.g., AI document generation, business templates) require the use of tokens. Tokens can be purchased directly or awarded through engagement bonuses or promotions.</li>
                          <li>Premium users may receive a monthly token allocation and benefit from reduced per-use pricing.</li>
                        </ul>
                        <p><strong>c. Refund Policy</strong></p>
                        <ul>
                          <li>Tokens are non-refundable once used.</li>
                          <li>Subscription payments are refundable only within 48 hours of initial purchase or renewal, provided that no tokens or premium services have been used during that period.</li>
                          <li>Refunds are not granted for partial usage or unintentional renewals after the 48-hour window.</li>
                        </ul>
                        <p><strong>d. Downgrades &amp; Cancellations</strong></p>
                        <ul>
                          <li>You may downgrade to a Basic plan at any time. Downgrades take effect at the end of the current billing cycle.</li>
                          <li>Upon downgrading, access to Premium features — including courses, Lift AI discounts, and tools — will be removed immediately unless otherwise stated.</li>
                        </ul>
                        <p><strong>e. Pricing Changes</strong></p>
                        <ul>
                          <li>We may revise our pricing or token packages with prior notice. Continued use of the platform after such changes indicates your acceptance of the new rates.</li>
                        </ul>
                      </div>

                      <div id="disclaimers-limitations">
                        <h2>9. Disclaimers &amp; Limitations of Liability</h2>
                        <p>
                          OpEn provides business support, tools, and AI-powered resources for educational and strategic use only. While we strive to deliver accurate and actionable insights, we do not make guarantees regarding business outcomes.
                        </p>
                        <p><strong>a. General Disclaimer</strong></p>
                        <ul>
                          <li>The platform, including Lift AI, training modules, community content, and business tools, is provided “as is” and “as available” without warranties of any kind — express or implied.</li>
                          <li>We do not guarantee that outputs, advice, or recommendations will be error-free, legally sufficient, or suitable for your specific business scenario.</li>
                        </ul>
                        <p><strong>b. AI-Specific Disclaimer</strong></p>
                        <ul>
                          <li>Lift AI and other AI tools rely on user input and natural language models. OpEn is not responsible for factual inaccuracies, misinterpretations, or decisions made based on AI-generated content.</li>
                          <li>You should consult a licensed professional for legal, financial, regulatory, or operational decisions before implementation.</li>
                        </ul>
                        <p><strong>c. Platform Availability</strong></p>
                        <ul>
                          <li>We strive for continuous uptime but do not guarantee that the platform will be free from interruptions, delays, or technical failures. Temporary downtime for maintenance or unforeseen outages may occur.</li>
                        </ul>
                        <p><strong>d. Limitation of Liability</strong></p>
                        <ul>
                          <li>To the maximum extent permitted by law, OpEn and its affiliates shall not be liable for any direct, indirect, incidental, or consequential damages arising from:</li>
                          <ul>
                            <li>Use or misuse of the platform</li>
                            <li>Inability to access features due to downtime</li>
                            <li>Errors in AI outputs or third-party tool integrations</li>
                            <li>Loss of data, profits, or business opportunities</li>
                          </ul>
                        </ul>
                        <p><strong>e. Jurisdiction-Specific Limits</strong></p>
                        <ul>
                          <li>Some jurisdictions may not allow certain limitations of liability, so these disclaimers may not fully apply to you. In such cases, our liability will be limited to the minimum extent permitted by law.</li>
                        </ul>
                      </div>

                      <div id="third-party-integrations">
                        <h2>10. Third-Party Platforms &amp; Integrations</h2>
                        <p>
                          The OpEn platform includes links to and integrations with third-party tools, services, and platforms to support your entrepreneurial journey. These services operate independently and are not governed by this Terms of Use agreement.
                        </p>
                        <p><strong>a. External Tool Access</strong></p>
                        <ul>
                          <li>When you use features like the Business Tools Directory or Lift AI (which may rely on external AI infrastructure), you may be redirected or connected to third-party platforms.</li>
                          <li>These services are subject to their own terms of service, data policies, and privacy practices, which you are encouraged to review independently.</li>
                        </ul>
                        <p><strong>b. Payment Processors</strong></p>
                        <ul>
                          <li>Subscription and token purchases may be handled by third-party payment gateways. These processors may collect and retain your payment details in accordance with their own security and compliance obligations.</li>
                        </ul>
                        <p><strong>c. App Stores &amp; Mobile Integrations</strong></p>
                        <ul>
                          <li>The OpEn mobile app may be accessed via Apple App Store or Google Play, and subject to additional terms imposed by those platforms.</li>
                        </ul>
                        <p><strong>d. Limitation of Liability</strong></p>
                        <ul>
                          <li>OpEn is not liable for any issues, damages, or losses resulting from your use of third-party services — including outages, inaccuracies, failed transactions, or data misuse by external providers.</li>
                        </ul>
                      </div>

                      <div id="termination-suspension">
                        <h2>11. Termination, Suspension &amp; Account Closure</h2>
                        <p>
                          We reserve the right to terminate, suspend, or restrict access to your account and services at our sole discretion if you violate these Terms or misuse the platform.
                        </p>
                        <p><strong>a. Grounds for Termination or Suspension</strong></p>
                        <ul>
                          <li>Violation of these Terms of Use</li>
                          <li>Abuse of Lift AI or token systems</li>
                          <li>Harassment or misconduct in Tribes or MyTribers</li>
                          <li>Attempted fraud, payment reversals, or impersonation</li>
                          <li>Use of platform for illegal or unauthorized activity</li>
                        </ul>
                        <p><strong>b. Effect of Termination</strong></p>
                        <ul>
                          <li>If your account is terminated, you lose access to your dashboard, courses, AI history, community participation, and purchased tokens.</li>
                          <li>No refunds will be issued for remaining subscription time or unused tokens unless required by law.</li>
                        </ul>
                        <p><strong>c. User-Initiated Account Deletion</strong></p>
                        <ul>
                          <li>You may delete your account at any time from your settings or by submitting a request to <a href="mailto:info@openpreneurs.business">info@openpreneurs.business</a>.</li>
                          <li>Upon deletion, your data will be handled in accordance with our Privacy Policy.</li>
                        </ul>
                        <p><strong>d. Appeals</strong></p>
                        <ul>
                          <li>If you believe your account was terminated or suspended in error, you may appeal by contacting support at <a href="mailto:info@openpreneurs.business">info@openpreneurs.business</a>.</li>
                        </ul>
                      </div>

                      <div id="governing-law-changes-contact">
                        <h2>12. Governing Law, Changes to Terms &amp; Contact Information</h2>
                        <p><strong>a. Governing Law</strong></p>
                        <p>
                          These Terms of Use shall be governed by and interpreted in accordance with the laws of Ontario, Canada, without regard to conflict of law principles. Any legal action arising out of or related to your use of the OpEn platform must be filed in a court of competent jurisdiction within Ontario.
                        </p>
                        <p><strong>b. Updates to Terms</strong></p>
                        <p>
                          We may update these Terms from time to time to reflect changes in our services, technology, legal obligations, or business operations. When material changes are made, we will notify you via email or in-platform notifications and update the “Last Revised” date at the top of this document. Continued use of the platform after changes are posted indicates your acceptance of the updated Terms.
                        </p>
                        <p><strong>c. Contact Information</strong></p>
                        <p>
                          If you have questions about these Terms or wish to reach us for any legal inquiries, please contact:<br />
                          📧 <a href="mailto:info@openpreneurs.business">info@openpreneurs.business</a>
                        </p>
                      </div>

                    </div>
                  </div>
                  {/* End Terms Content */}
                </div>
              </div>
            </div>
          </div>
        </section>
      </main>
    </Layout>
  );
}
